# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-10 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(max_length=200)),
                ('tagline', models.CharField(blank=True, max_length=500, null=True)),
                ('genre', models.CharField(choices=[('action', 'Action'), ('adventure', 'Adventure'), ('animation', 'Animation'), ('comedy', 'Comedy'), ('drama', 'Drama'), ('fantasy', 'Fantasy'), ('historical', 'Historical'), ('horror', 'Horror'), ('mystery', 'Mystery'), ('romance', 'Romance'), ('science_fiction', 'Science Fiction'), ('thriller', 'Thriller')], max_length=100)),
                ('director', models.CharField(max_length=100)),
                ('outline', models.TextField()),
                ('poster', models.ImageField(upload_to='')),
                ('release_date', models.DateTimeField()),
                ('trailer', models.TextField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
