# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-11 08:15
from __future__ import unicode_literals

from django.db import migrations, models
import movie.models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20170610_1904'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'verbose_name': 'Movie', 'verbose_name_plural': 'Movies'},
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(upload_to=movie.models.upload_location),
        ),
    ]
