# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-11 11:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_auto_20170611_1516'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-release_date', '-created', '-updated'], 'verbose_name': 'Movie', 'verbose_name_plural': 'Movies'},
        ),
    ]
