# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-11 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_auto_20170611_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='trailer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
