# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-11 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_auto_20170611_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='writer',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
